apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    <h1>Hello World!</h1>
    <footer>
      Cluster: CLUSTER_NAME, Node: NODE_NAME
    </footer>
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            sub_filter_once off;
            sub_filter 'CLUSTER_NAME' '$env_CLUSTER_NAME';
            sub_filter 'NODE_NAME' '$env_NODE_NAME';
        }
    }
